//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemExam2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materials()
        {
            this.product_materials = new HashSet<product_materials>();
        }
    
        public int material_id { get; set; }
        public string material_name { get; set; }
        public int material_type_id { get; set; }
        public double price { get; set; }
        public int amount { get; set; }
        public int min_amount { get; set; }
        public int amount_per_package { get; set; }
        public int measurment_id { get; set; }
    
        public virtual material_types material_types { get; set; }
        public virtual measurments measurments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_materials> product_materials { get; set; }
    }
}
