//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemExam2.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_materials
    {
        public int product_material_id { get; set; }
        public int product_id { get; set; }
        public int material_id { get; set; }
        public double amount_of_material { get; set; }
    
        public virtual materials materials { get; set; }
        public virtual products products { get; set; }
    }
}
