//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemExam2.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.product_materials = new HashSet<product_materials>();
        }
    
        public int product_id { get; set; }
        [Required(ErrorMessage = "Тип продукта должен быть указан")]
        [Range(1, 4)]
        public int product_type_id { get; set; }


        [Required(ErrorMessage = "Наименование продукта должно быть указано")]
        [StringLength(128, MinimumLength = 1)]
        public string name_of_product { get; set; }

        [Required(ErrorMessage = "Артикул должен быть указан")]
        [Range(1, 2147483647)]
        public int article { get; set; }


        [Required(ErrorMessage = "Минимальная цена должна быть указана")]
        [Range(0.01, 1000000)]
        public double min_price { get; set; }


        [Required(ErrorMessage = "Ширина должна быть указана")]
        [Range(0.05, 1000)]
        public double wide { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_materials> product_materials { get; set; }
        public virtual product_types product_types { get; set; }
    }
}
