//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemExam2.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Wallpaper_FactoryEntities : DbContext
    {
        public static Wallpaper_FactoryEntities _context;

        public static Wallpaper_FactoryEntities GetContext()
        {
            if (_context == null)
                _context = new Wallpaper_FactoryEntities();
            return _context;
        }
        public Wallpaper_FactoryEntities()
            : base("name=Wallpaper_FactoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<material_types> material_types { get; set; }
        public virtual DbSet<materials> materials { get; set; }
        public virtual DbSet<measurments> measurments { get; set; }
        public virtual DbSet<product_materials> product_materials { get; set; }
        public virtual DbSet<product_types> product_types { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
